version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: passs
      POSTGRES_USER: user
      POSTGRES_DB: nest-db
    depends_on:
      - postgres
    networks:
      - testing

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: passs
      POSTGRES_USER: user
      POSTGRES_DB: nest-db
    networks:
      - testing

networks:
  testing:





