version: '3'
services:
  app:
    image: artembondarchuk/coding-test
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: passs
      POSTGRES_USER: user
      POSTGRES_DB: nest-db
    depends_on:
      - postgres
    networks:
      - testing

  postgres:
    image: postgres
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: passs
      POSTGRES_USER: user
      POSTGRES_DB: nest-db
    networks:
      - testing

networks:
  testing:





