version: 2
jobs:
  test:
    docker:
      - image: circleci/node
        environment:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: nest-app
          DB_USER: nest
          DB_PASSWORD: 123
      - image: circleci/postgres
        environment:
          POSTGRES_USER: nest
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: nest-todo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run UNIT test
          command: npm run test
      - run:
          name: Run E2E test
          command: npm run test:e2e

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
